name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r app/requirements.txt

      - name: Lint code
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 app/

      - name: Build Docker image
        run: docker build -t salmanahmad0469/task-manager-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push salmanahmad0469/task-manager-app:latest